#!/usr/bin/python3

def display_menu():
    print("Welcome to the Tourist Guide App")
    print("1. View all destinations")
    print("2. View destination details")
    print("3. Add a new destination")
    print("4. Exit")

def view_all_destinations(destinations):
    print("All Destinations:")
    for dest in destinations:
        print(dest)
